version: "3"

services:
  proxy_web:
    build: ./app
    working_dir: /proxy_web/app
    restart: always
    command: "uvicorn api:app --host 0.0.0.0 --port 9001 --reload"
    volumes:
      - .:/proxy_web
    ports:
      - "9001:9001"
